// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1, arg2) {
  return window['go']['main']['DesktopApp']['AddRepository'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['DesktopApp']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['main']['DesktopApp']['GetConnectionStatus']();
}

export function GetConnectionURLs() {
  return window['go']['main']['DesktopApp']['GetConnectionURLs']();
}

export function GetQRCodeData() {
  return window['go']['main']['DesktopApp']['GetQRCodeData']();
}

export function GetRepositories() {
  return window['go']['main']['DesktopApp']['GetRepositories']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['DesktopApp']['OpenDirectoryDialog']();
}

export function RemoveRepository(arg1) {
  return window['go']['main']['DesktopApp']['RemoveRepository'](arg1);
}

export function SwitchRepository(arg1) {
  return window['go']['main']['DesktopApp']['SwitchRepository'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['DesktopApp']['UpdateConfig'](arg1, arg2);
}
