// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRepository(arg1:string,arg2:string):Promise<main.Repository>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetConnectionURLs():Promise<Record<string, string>>;

export function GetQRCodeData():Promise<string>;

export function GetRepositories():Promise<Array<main.Repository>>;

export function OpenDirectoryDialog():Promise<string>;

export function RemoveRepository(arg1:string):Promise<void>;

export function SwitchRepository(arg1:string):Promise<void>;

export function UpdateConfig(arg1:string,arg2:any):Promise<void>;
